### ISSUE TITLE
How to conver the 1D Spectroscopy to image format

### ISSUE THREAD

**Issue by hmyao22** [conor-horgan/DeepeR#5]
Dear author, thank you for your excellent work

I am very interested in the denoising part. The article shows the denoised cell images. I am curious about how to convert 172,312 spectra into 11 cell images.

thank you for your attention

**Comment by conor-horgan** [comment]
Hi, thank you. I have updated the README with a link to the input and target cell images for denoising (see [here](https://github.com/conor-horgan/DeepeR/blob/master/README.md#raman-spectral-denoising)).
